language: c
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - liblua5.1-dev
      - liblua5.2-dev
      - lua5.1

env:
  global:
    - LUAROCKS=2.4.3

before_script:
  - source .travis/setenv_lua.sh
  - ./build.sh
  - make -f ljbuild.make name=hotcounters branch=bencher_hotcounters

script:
  - ./builds/nojit/luajit simplerunner.lua -c 1 -e scimark_fft -e scimark_sparse -e scimark_sor -e scimark_lu -e mandelbrot_bit
  - ./builds/normal/luajit simplerunner.lua --jitstats -c 3
  - ./builds/gc64/luajit simplerunner.lua -e capnproto_decode -c 3
  - ./builds/dualnum/luajit simplerunner.lua -c 3
  - ./builds/raptorjit/luajit simplerunner.lua --inprocess -e capnproto_decode -e moonscript -e fasta -c 3
  - ./builds/hotcounters/luajit simplerunner.lua -c 3
  - make -f ljbuild.make name=hotcounters clean pull build
  - make -f ljbuild.make name=hotcounters reset
  - make -f ljbuild.make name=hotcounters pull
  - make -f ljbuild.make name=hotcounters clean
