language: c
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - liblua5.1-dev
      - liblua5.2-dev
      - lua5.1

env:
  global:
    - LUAROCKS=2.4.3

before_script:
  - source .travis/setenv_lua.sh
  - ./build.sh
  - ./build_openresty.sh

script:
  - ./builds/normal/luajit simplerunner.lua --jitstats -c 3
