local action = {
  mixins = {
    "iter_annotate"
  }
}

local function printf(...)
  print(string.format(...))
end

function action.logparsed(jlog)
  for i, marker in ipairs(jlog.markers) do
    if marker.label == "BEGIN" then
      local stats = marker.stats
      assert(stats, "Iteration marker is missing stats generated by iter_annotate")
      printf("%d: %.4f, traces %d, aborts %s, exits %d, gcstate %s(%d)", marker.n, stats.time,
             stats.traces, stats.aborts, stats.exits, marker.gcstate or "pause", stats.gcstatecount)
    end
  end
end

return action
